config/routes.rb
Prioritize::Application.routes.draw do
  root :to => 'problems#index'
  resources :problems do
    resources :solutions
  end
  resources :categories

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :name, :description, :category_id
  
  has_many :solutions
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  attr_accessible :name, :notes
  
  belongs_to :problem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def new
    @problem = Problem.new
  end
  
  def create
    @problem = Problem.new(params[:problem])
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem }
      end
    end
  end
  
  def index
    @problems = Problem.all
  end
  
  def show
    @problem = Problem.find(params[:id])
    @solution = Solution.new
  end
  
  def edit
    @problem = Problem.find(params[:id])
  end
  
  def update
    @problem = Problem.find(params[:id])
    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to problem_path(@problem) }
      end
    end
  end
  
  def destroy
    @problem = Problem.find(params[:id])
    respond_to do |format|
      if @problem.destroy
        format.html { redirect_to problems_path }
      end
    end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def create
    @problem = Problem.find(params[:problem_id])
    @solution = @problem.solutions.build(params[:solution])
    respond_to do |format|
      if @solution.save
        format.html { redirect_to @problem }
      end
    end
  end
  
  def show
    @problem = Problem.find(params[:problem_id])
    @solution = @problem.solutions.build
  end
  
  def new
    @solution = Solution.new
  end
  
  def destroy
    @problem = Problem.find(params[:id])
    @solution = @problem.solutions.find(params[:problem_id])
    respond_to do |format|
      if @solution.destroy
        format.html { redirect_to @problem }
      end
    end
  end
  
  def edit
    @solution = Solution.find(params[:id])
    @problem = Problem.find(params[:problem_id])
  end
  
  def update
    @problem = Problem.find(params[:problem_id])
    @solution = Solution.find(params[:id])
    respond_to do |format|
      if @solution.update_attributes(params[:solution])
        format.html { redirect_to @problem }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown(text)
    Redcarpet.new(text).to_html.html_safe
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prioritize</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "custom", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=IM+Fell+French+Canon+SC' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="navbar">
		<ul>
			<li><%= link_to 'Problems', problems_path %></li>
			<li><%= link_to 'New Problem', new_problem_path %></li>
		</ul>
		<h1>Categories</h1>
		<ol>			
			<li>Mobile App</li>
			<li>Web App</li>
			<li>Physical Good</li>
			<li>General Problem</li>
		</ol>
	</div>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/problems/edit.html.erb
<h1>Edit Problem</h1>
<%= form_for @problem do |f| %>
<p>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :category_id %><br/>
	<%= f.number_field :category_id %>
</p>
<p>
	<%= f.label :description %><br/>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/problems/index.html.erb
<head>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('.toggle-content').hide();

	$('.toggle-control')
	 .addClass('clickable')
	 .bind('click', function() {
		var $control = $(this);
		var $parent = $control.parents('.toggle-unit');

		$parent.toggleClass('expanded');
		$parent.find('.toggle-content').slideToggle();

		// if control has HTML5 data attributes, use to update text
		if ($parent.hasClass('expanded')) {
			$control.html($control.attr('data-expanded-text'));
		} else {
			$control.html($control.attr('data-text'));
		}
	})
});
</script>
</head>
	<h1>Mobile App</h1>
	<ol>
	<% @problems.each do |f| %>
	<% if f.category_id == 1 %>
<div class="toggle-unit">
	<li><h2 class="toggle-control"><%= link_to f.name, problem_path(f), :id => 'problemlink'%> <% if f.description.size > 0 %>(expand)<% end %> <span id="solutionsize"><%= f.solutions.size.to_s %> Solutions</span></h2>
	<div class="toggle-content">
		<%= markdown(f.description) %>
	</div><!-- /.toggle-content --></li>
</div><!-- /.toggle.unit -->
	<% end %>
	<% end %>
	</ol>
	
	<h1>Web App</h1>
	<ol>
	<% @problems.each do |f| %>
	<% if f.category_id == 2 %>
<div class="toggle-unit">
	<li><h2 class="toggle-control"><%= link_to f.name, problem_path(f), :id => 'problemlink'%> <% if f.description.size > 0 %>(expand)<% end %> <span id="solutionsize"><%= f.solutions.size.to_s %> Solutions</span></h2>
	<div class="toggle-content">
		<%= markdown(f.description) %>
	</div><!-- /.toggle-content --></li>
</div><!-- /.toggle.unit -->
	<% end %>
	<% end %>
	</ol>
	
	<h1>Physical Good</h1>
	<ol>
	<% @problems.each do |f| %>
	<% if f.category_id == 3 %>
<div class="toggle-unit">
	<li><h2 class="toggle-control"><%= link_to f.name, problem_path(f), :id => 'problemlink'%> <% if f.description.size > 0 %>(expand)<% end %> <span id="solutionsize"><%= f.solutions.size.to_s %> Solutions</span></h2>
	<div class="toggle-content">
		<%= markdown(f.description) %>
	</div><!-- /.toggle-content --></li>
</div><!-- /.toggle.unit -->
	<% end %>
	<% end %>
</ol>

	<h1>General Problem</h1>
	<ol>
	<% @problems.each do |f| %>
	<% if f.category_id == 4 %>
<div class="toggle-unit">
	<li><h2 class="toggle-control"><%= link_to f.name, problem_path(f), :id => 'problemlink'%> <% if f.description.size > 0 %>(expand)<% end %> <span id="solutionsize"><%= f.solutions.size.to_s %> Solutions</span></h2>
	<div class="toggle-content">
		<%= markdown(f.description) %>
	</div><!-- /.toggle-content --></li>
</div><!-- /.toggle.unit -->
	<% end %>
	<% end %>
</ol>

app/views/problems/new.html.erb
<h1>New Problem</h1>
<%= form_for @problem do |f| %>
<p>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :category_id %><br/>
	<%= f.number_field :category_id %>
</p>
<p>
	<%= f.label :description %><br/>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/problems/show.html.erb
<h1><%= @problem.name %></h1><%= link_to 'Edit', edit_problem_path(@problem) %> <%= link_to 'Destroy', problem_path(@problem), :method => :delete %>
<p>
	<%= markdown(@problem.description) %>
</p>
<ol>
	<% @problem.solutions.each do |s| %>
	<li><h3><%= s.name %></h3>
		<p><%= markdown(s.notes) %></p>
		<%= link_to 'Edit', edit_problem_solution_path(@problem, s) %> <%= link_to 'destroy', problem_solution_path(s), :method => :delete %></li>
	<% end %>
</ol>

<h1>New Solution</h1>
<%= form_for [@problem, @solution] do |f| %>
<p>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :notes %><br/>
	<%= f.text_area :notes %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/solutions/edit.html.erb
<h1>Edit Solution</h1>
<%= form_for [@problem, @solution] do |f| %>
<p>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :notes %><br/>
	<%= f.text_area :notes %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>